More bugfixes with testing

diff --git a/testing/build/makefile b/testing/build/makefile
--- a/testing/build/makefile
+++ b/testing/build/makefile
@@ -4,10 +4,13 @@ SHELL=/bin/bash
 
 include $(INCLUDES)
 
-EXAMPLES=$(wildcard example*.xc) #$(filter-out $(wildcard example*error*.xc), $(wildcard example*.xc))
+EXAMPLES=$(filter-out $(wildcard example*error*.xc), $(wildcard example*.xc))
 OBJECTS=$(EXAMPLES:.xc=.o)
 EXECUTABLES=$(EXAMPLES:.xc=.out)
 TESTS=$(EXAMPLES:.xc=.test)
+
+AUTOTESTS_SRC=$(wildcard example*.xc)
+AUTOTESTS=$(AUTOTESTS_SRC:.xc=.c) $(TESTS)
 
 # Also building all object files to speed up compilation when rewrite_driver.xc changes
 all: $(EXECUATBLE_DEPENDS) $(OBJECTS) $(EXECUTABLES) $(TESTS)
@@ -24,13 +27,19 @@ endif
 
 %.c: %.xc $(JAR_NAME)
 ifdef TESTING
-	echo -n "Compiling $<... "
+	echo -n "Translating $<... "
 	if [ -z $(findstring error, $<) ] ; then { java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS) &> $@.test.out && echo "passed" || { echo "failed" ; touch .tests_failed ; } ; } ; else { java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS) &> $@.test.out && { echo "failed (did not error)" ; touch .tests_failed ; } || echo "passed (did not compile)" ; } ; fi
 else
 	java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS)
 endif
 	mv $(patsubst %.xc, %.pp_out.c, $<) $@
 	rm $(patsubst %.xc, %.gen_cpp, $<)
+
+ifdef TESTING
+%.o: %.c
+	echo -n "Compiling $<... "
+	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< &> $@.test.out && echo "passed" || (echo "failed" ; touch .tests_failed)
+endif
 
 %.out: %.o $(EXECUATBLE_DEPENDS)
 	$(CC) $(LDFLAGS) $< $(LOADLIBES) $(LDLIBS) -o $@
@@ -49,7 +58,7 @@ endif
 tests:
 	@echo "Testing $(shell basename `pwd`)..."
 	@rm -f *.test .tests_failed
-	-@./make -s TESTING=true $(TESTS) 2>/dev/null ||:
+	-@./make -s TESTING=true $(AUTOTESTS) 2>/dev/null ||:
 	@if [ -f .tests_failed ] ; then echo -e "\e[91mSome tests failed\e[39m" ; else echo -e "\e[92mAll tests passed\e[39m" ; fi
 
 clean:
