Fixed bug with handling tests that compile when they shouldn't

diff --git a/testing/build/makefile b/testing/build/makefile
--- a/testing/build/makefile
+++ b/testing/build/makefile
@@ -28,7 +28,7 @@ endif
 %.c: %.xc $(JAR_NAME)
 ifdef TESTING
 	echo -n "Translating $(shell basename $<)... "
-	if [ -z $(findstring error, $<) ]; then (java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS) &> $@.test.out && echo "passed" || (echo "failed"; touch .tests_failed; exit 2)) else (java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS) &> $@.test.out && (echo "failed (did not error)"; touch .tests_failed; exit 3) || echo "passed (did not compile)") fi
+	if [ -z $(findstring error, $<) ]; then (java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS) &> $@.test.out && echo "passed" || (echo "failed"; touch .tests_failed; exit 2)) else if java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS) &> $@.test.out; then echo "failed (did not error)"; rm $@; touch .tests_failed; exit 3; else echo "passed (did not compile)"; fi; fi
 else
 	java $(JAVA_FLAGS) -jar $(JAR_NAME) $< $(CPPFLAGS)
 endif
